[package]
name = "log-map-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
log-map = { path = "../log-map" }
log-server-types = { path = "../types" }
tokio = { version = "1", features = ["full"] }
